version: '3.8'

services:
  model:
    build:
      context: .
      dockerfile: Dockerfile-model
    container_name: model_service
    restart: always

  api:
    build:
      context: .
      dockerfile: Dockerfile-api
    container_name: api_service
    ports:
      - "5000:5000"
    depends_on:
      - model
    restart: always

  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    container_name: frontend_service
    ports:
      - "8501:8501"
    depends_on:
      - api
    restart: always
