FROM python:3.9-slim

WORKDIR /app

COPY desafio_premier_soft.py /app/
COPY requirements.txt /app/

RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "desafio_premier_soft.py"]
