FROM python:3.9-slim

WORKDIR /app

COPY app_streamlit.py /app/
COPY requirements.txt /app/

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8501

CMD ["streamlit", "run", "app_streamlit.py", "--server.port=8501", "--server.enableCORS=false"]
